import React, { useEffect } from 'react';
import Head from 'next/head';
import Router from 'next/router';



export default function Home() {

  useEffect(()=>{
    Router.push("/dashboard")
  })
  return (
   <>
    <Head>
        <title>coin-desk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      
   </>
  );
}
